### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by toonsgy** [Togg-streamdeck/dcs#1]
hi, 

It seems like the jester directory image ( from the main F14 menu) is missing. 
Big thanks for your awesome work.

**Comment by Togg-streamdeck** [comment]
I updated the profile, it was a little bit old. Now you have "jester nav", "jester rdr" and "jester lantirn" (when jester lantirn will do something)

**Comment by toonsgy** [comment]
What a quick fix. You've done a great job man. Again, thank and keep doing what you do. see you
