### ISSUE TITLE
Usage request

### ISSUE THREAD

**Issue by matt-cahill** [Togg-streamdeck/dcs#2]
Hi,

I'd like to use some of your icons in documentation and a tutorial for this project https://github.com/DCSFlightpanels/DCSFlightpanels.

I noted that you do not have an open source licence attached to this project so I'm just checking you are ok with me doing so? I'll attribute your work in all cases and link to this repo.

Kind regards,

Matt

**Comment by Togg-streamdeck** [comment]
Hi

You can use the icons, it is ok. I know DCSFlightPanels even I finally built my own panels.

You can design your own buttons with the file buttonModel.svg  if you want.

Regards

**Comment by matt-cahill** [comment]
Thank you very much @Togg-streamdeck and thank you for the excellent icons :)
